append_unmatched: true

nav:
  - Home: index.md
  - Guides: guides
  - Installation: installation.md
  - Configuration: configuration.md
  - FAQs: faq.md
  - Release Notes: release-notes.md
  - Troubleshooting: troubleshooting.md
  - Abbreviations & Glossary: abbreviations.md
  - Downloads: downloads.md
  - Tags: tags.md
